### ISSUE TITLE
Floating sidebar causes footer border to disappear

### ISSUE THREAD

**Issue by ravimakhija** [quarto-dev/quarto#126]
## Issue Description

It seems that using a floating `sidebar` in Quarto sets the `floating` class on the `body` element, which in turn causes bootstrap to not apply `border-top` to `nav-footer` (see below), in turn causing the footer border to not show up. 

```
body:not(.floating) .nav-footer {
    border-top: 1px solid #dee2e6;
}
```

We are using custom CSS as a workaround currently (https://github.com/datascijedi/website/pull/79). 

## Reproducible Example

_quarto.yml
```yml
project:
  type: website
  output-dir: _site

website:
  sidebar:
    - title: "Page 1 Sidebar"
      style: "floating"
      # style: "docked"
      border: true
      collapse-level: 2
      align: left
      contents:
        - text: "Page 1"
          file: page1.qmd

  page-footer:
    border: true
    left: "Left Stuff"
```

page1.qmd
```md
# Page 1
```
