### ISSUE TITLE
render targets in _quarto.yml not used

### ISSUE THREAD

**Issue by iusgit** [quarto-dev/quarto#15]
Hi,

I wrote an extension and I'am using it with a special `format` notion in the `_quarto.yml` file:

```
project:
  type: book
  # output-dir: rendered_docs

lang: de-DE

book:
  title: "Title"
  author: "Author"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - content/Chapter_01.qmd
    - content/References.qmd
  appendices: 
    - content/Appendix_01.qmd

bibliography: resources/literature/references.bib

format:
  extension-html: default
  extension-docx: default
  extension-pdf: default

editor: 
  render-on-save: true
```

When I either *save* one of the chapter documents or use the render shortcuts 

<img width="227" alt="Bildschirmfoto 2022-11-04 um 10 09 57" src="https://user-images.githubusercontent.com/91615683/199935623-3fd09611-cb33-4164-8950-140f4da80f3f.png">

the definition in the _quarto.yml isn't used but the default `--to docx,html,pdf` targets. 

Is this by design?
Can I configure quarto-vscode to use by default the targets in the _quarto.yml file?

Thanks,
Maarten
