### ISSUE TITLE
No render button in VS code

### ISSUE THREAD

**Issue by jinzzasol** [quarto-dev/quarto#285]
# Bug description

Render button disappeared in VS code
<img width="1348" alt="271255488-072af7dd-1bbc-480d-9078-d4fa7668b893" src="https://github.com/quarto-dev/quarto/assets/49014051/6578190b-bd0d-4b72-8884-9cfad90238ff">

# Steps to reproduce

I don't know how to reproduce this. It just happened.

# Expected behavior

There should be Render button and Render pdf, Render html and so on

# Actual behavior

No Render button when qmd file is in active

# Your environment

- IDE: VS Code
- OS: Mac OS 14.0 Sonoma

Quarto check output

[✓] Checking versions of quarto binary dependencies...
Pandoc version 3.1.1: OK
Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
Version: 1.3.450
Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
Version: 3.10.12 (Conda)
Path: /Users/j*****/miniconda3/bin/python
Jupyter: 5.3.1
Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

```bash
  Unable to locate an installed version of R.
  Install R from https://cloud.r-project.org/
```

**Comment by jinzzasol** [comment]
#editors #vscode

**Comment by jjallaire** [comment]
I think what is happening here is that another extension has contributed the "Run Code" action, and that has taken over the run menu (there can only be one run menu, if Quarto is the only extension contributing a run action then it will say "Preview" (formerly "Render", that changed recently). Otherwise it will just show that arrow. To find out which extension you can execute the **Help: Extension Bisect** command (although if you want to keep using this extension I don't think there is a way to get "Preview" back on the toolbar). Note that you can use the Cmd+Shift+K keyboard shortcut, or alternatively setup "Render on Save".

**Comment by jinzzasol** [comment]
@mcanouil Thanks, so I ran the **Help: Start Extension Bisect** then it identified **Quarto** extension as a cause. This is not correct. There should be another extension causing this issue. I personally uninstalled the ones that were suspicious, but it didn't solve the issue.

![image](https://github.com/quarto-dev/quarto/assets/49014051/42ff433d-7e99-4882-8c6e-654266eb992b)

**Comment by jjallaire** [comment]
I think you want to first uninstall Quarto and then confirm that the "Run Code" button/menu is still present (so contributed by another extension). _Then_, run the Extension Bisect and see which extension is contributing that menu item.

**Comment by jinzzasol** [comment]
With Quarto installed, there is still "Run Code" button. Do you think I need to uninstall it and run **Extension Bisect**. FYI, I just uninstalled the extension and reinstalled it - nothing changed.

**Comment by remlapmot** [comment]
If I remember correctly that is provided by the Code Runner extension <https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner>

**Comment by jinzzasol** [comment]
So, I just uninstalled Quarto and check the "Run Code" button and it is there. I uninstalled **Code Runner** extension but nothing changes. 

One thing I found weird is that from the command palette, there should be multiple **Render** options, but they are gone. So I was thinking that Quarto has been changed something.

![image](https://github.com/quarto-dev/quarto/assets/49014051/74444b7f-c902-4881-adf0-5cf1f1c38fd3)

**Comment by remlapmot** [comment]
After uninstalling or disabling the Code Runner extension you need to click the *Reload Required*

<img width="382" alt="Screenshot 2023-09-28 at 17 50 42" src="https://github.com/quarto-dev/quarto/assets/3777473/f8b3bd19-9f15-474f-ab3c-e01c0790ea68"> 

I get the Preview back after reloading (after disabling Code Runner)

<img width="421" alt="Screenshot 2023-09-28 at 17 48 42" src="https://github.com/quarto-dev/quarto/assets/3777473/a523323d-ee7c-49ab-9fbb-9a0e49310d19">

**Comment by jinzzasol** [comment]
@remlapmot I think you might misunderstood the issue. I have a Preview button. I am missing the "Render" button with multiple options to choose from, i.e., "Render PDF", "Render HTML", "Render DOCX" which are enabled with the Quarto extension.

**Comment by jjallaire** [comment]
We have recently decomposed and refined our Preview and Render commands to better match what's in the CLI as well as to support selecting *any* format declared in a document (not strictly limited to Docx and Pdf). You can see docs on this here: https://quarto.org/docs/tools/vscode.html#render-and-preview

That said, I think people have found the loss of the "built in" Docx and Pdf menu items confusing. As things currently stand you can get these back by adding them to your document and invoking **Quarto: Preview Format**. I am currently in the process of sorting out how to get these back into the UI so people always have them even if not declared in the document.

**Comment by jinzzasol** [comment]
What you just said is that there is no "Render" button in VS code anymore. So this is a current feature that I have to use. Is this correct? Nothing to do with other extensions or VS code settings?

What I used to do with the Render button with multiple options is that I create a `_quarto.yml` file in the project directory, and choose the format to render depending on the required document format. Some people want to have `docx`, others want `pdf`. Also, I just rendered the document to preview it by just clicking the button. Now the problem is that there is one preview button, and I have multiple format setups in `yml`, when I click the button, it generates all of the formats I defined in the `yml` file. Or, I have to use a command line every time with a specific command to see the document in the format that I want. 

**yml example**
```
format:
  html:
    embed-resources: true
    text-align: justify
    text-justify: inter-word
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    code-link: true
    code-line-numbers: true
    code-fold: true
    fig-pos: "H"

  pdf:
    pdf-engine: pdflatex
    include-in-header:  
      - text: |
        \usepackage{amsmath}
    papersize: letter
    geometry:
      - left=20mm
      - right=20mm
    fig-pos: "H"
    embed-resources: true
    text-align: justify
    text-justify: inter-word
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    code-link: true
    code-line-numbers: true
    code-fold: true

  docx:
    reference-doc: custom-reference-doc.docx
```
