### ISSUE TITLE
Feature Request: Option to Suppress Automatic Bibliography in PDF Output

### ISSUE THREAD

**Issue by olearydj** [quarto-dev/quarto#386]
I'm currently using Quarto to generate both HTML and PDF documents from the same source. For the PDF version, I need to manually manage the bibliography using biblatex and biber due to specific formatting requirements and the need for back-references. However, I've encountered an issue where Quarto automatically generates a bibliography section at the end of my PDF documents, despite my custom configuration. This results in the bibliography being duplicated: once where I have manually inserted it using LaTeX commands, and once automatically by Quarto.

I would like an option in the Quarto configuration that allows me to suppress the automatic bibliography generation when rendering to PDF. This option would prevent Quarto from automatically adding a bibliography section, enabling me to fully control the bibliography placement and formatting through LaTeX.

For example, an option in the _quarto.yml could be:

```yaml
pdf:
  bibliography: none  # or some similar keyword to indicate suppression
```

I have tried various workarounds, such as modifying the LaTeX template to remove bibliography commands. However, these methods have not been successful in preventing the automatic inclusion of the bibliography by Quarto. It seems like the bibliography rendering is done outside of the config files.

Here are the relevant sections of my `_quarto.yml` file; some sections omitted (...) for brevity:

```yaml
book:
...
  chapters:
    - index.qmd
...
    - 27-references.qmd
  appendices:
    - 31-irb.qmd
...

bibliography: references.bib
csl: "csl/apa7-single-spaced.csl"

...

  pdf:
    link-citations: true
    cite-method: "biblatex"
    biblio-style: "apa"
    biblatexoptions: 
      - "backend=biber"
      - "backref=true"
    template: tex/template.tex
```

Options for html output are included in the same file, but nothing else specific to bibliography generation. I normally render to HTML for a quick preview, and occasionally to PDF.

Here are the contents of `27-references.qmd` which is used to generate the appropriate content based on render target:

```md
::: {.unlisted #27-references}
# References

<!-- For PDF output -->
::: {#refs .latex}
\begingroup
\raggedright
\printbibliography[heading=none]
\endgroup
:::

<!-- For HTML output -->
::: {#refs .html}
:::
:::
```

That last bit is pretty damn clever, if I do say so myself. H/T to ChatGPT4 for being a know-it-all.

With this setup I get everything exactly as I'd like it, except that the bibliography is duplicated at the end of everything else.

Thanks!
