### ISSUE TITLE
[Feature request] [Accessibility]: Meaningful aria-label for search icon

### ISSUE THREAD

**Issue by signekb** [quarto-dev/quarto#468]
## Feature Request/Accessibility: Meaningful aria-label for search icon

Currently, there doesn't seem to be an easy way of adding an aria-label to the search icon of a Quarto website, which makes it difficult for screen readers to locate. 

For example, when I use Google Chrome's Lighthouse accessibility check on quarto.org, I get the following reports in relation to the search icon:

![image](https://github.com/quarto-dev/quarto/assets/40836345/81675a8d-fbe3-4fa1-a4f3-91e66129a85a)

![image](https://github.com/quarto-dev/quarto/assets/40836345/b1f081da-236f-4161-875b-6c9e2647aab9)

It would be nice if it was possible, like with other navbar icons, to add an aria-label to the search icon, like with other navbar icons like so:

```
---
website:
  navbar:
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
---
```

Alternatively, it would be even nicer, if a meaningful aria-label like "Search" was added by default.
