### ISSUE TITLE
VSCode or RStudio: Table caption appears within the table

### ISSUE THREAD

**Issue by Coding4Sec** [quarto-dev/quarto#561]
Strange behavior and showstopper to use quarto for my reports:

In the preamble the placement of the caption of a table is set to bottom:

```yaml
format:
  pdf:
    toc: true
    toc-depth: 3
    lof: true
    lot: true
    geometry:
      - top=30
      - left=40mm
    execute:
      echo: false
    tbl-cap-location: bottom
```

Inserting a table like:

```markdown
Test table

| Quelle  | Left | 
|---------|:-----|
| 12      | 12   |
| 123     | 123  | 
| 1       | 1    |


: table caption
```

gives the following:
![Image](https://github.com/user-attachments/assets/1da5c11d-4a4f-4033-9b61-1daa735ae872)

not sure how to fix this. This shows up on Rstudio and VScode. 
Rick
