### ISSUE TITLE
Problems with rendering author and title in HTML and BibTeX

### ISSUE THREAD

**Issue by praalhans** [quarto-dev/quarto#690]
### Bug description

Currently in the process of moving my publication over to Quarto: many thanks for the excellent software!
 
I have a Quarto document with the following meta-data (minimal example):
```
---
author:
  - name:
      given: Hans-Dieter A.
      family: Hiep
    url: /author/hans-dieter-hiep/
    orcid: 0000-0001-9677-6644
  - name:
      given: Frank S.
      family: Boer
      non-dropping-particle: de
    url: /author/frank-de-boer/
    orcid: 0000-0003-3950-6271
title: A sound and complete proof system for separation logic (part&nbsp;1)
...
```
the title displays correctly, in the sense that the `&nbsp;` is replaced in the HTML format by a non-breaking space. This is important when showing the article in a grid listing, so that "(part 1)" stays together, and that the "(part" and "1)" do not span multiple lines when screen space is limited.

**Issue 1.** In the HTML output, although the title is displayed correctly, the authors are displayed as:

> Authors
> Hans-Dieter A. Hiep
> Frank S. Boer

(here the particle "de" is missing from the last name)

When the BibTeX citation block is generated, it shows up as:
```
@article{hiep2024,
  author = {Hiep, Hans-Dieter A. and de Boer, Frank S.},
  title = {A Sound and Complete Proof System for~Separation~Logic
    (Part\ 1)},
  ...
```
Notice how, correctly, the non-breaking space is replaced in LaTeX by `\ `. But also notice how additional non-breaking spaces `~` were added in the phrase "for separation logic".

**Issue 2.** In the text that follows the BibTeX citation, the authors look good, but the title is rendered incorrectly:

> For attribution, please cite this work as:
> Hans-Dieter A. Hiep and Frank S. de Boer. A sound and complete proof system for separation logic (part&amp;nbsp;1). dr. heap (June 2024). https://doi.org/10.59350/2gkd1-c0k49

Moreover, in the metadata generated for Google Scholar, there is also a problem with the title:
```
<meta name="citation_title" content="A sound and complete proof system for&nbsp;separation&nbsp;logic (part&amp;amp;nbsp;1)">
<meta name="citation_author" content="Hans-Dieter A. Hiep">
<meta name="citation_author" content="Frank S. de Boer">
```
where the `&nbsp;` of the title is now turned into `&amp;amp;nbsp;` (instead of representing a non-breaking space `&nbps;`).

Hope these issues can be resolved!

### Environment

Running Quarto version 1.6.33.
